# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  push:
    paths-ignore:
      - "**/README.rst"
      - "**/dependabot.yml"
    branches: [version-2.01]
  pull_request:
    paths-ignore: 
      - "**/README.rst"
      - "**/dependabot.yml"
    branches: [version-2.01]

concurrency: CI-2.01

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install dependencies
        run: |
          sudo apt-get -y install libxml2-dev libxslt-dev libxslt1-dev python3-dev python3-lxml libxml2-utils
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -r requirements.txt

      - name: flake8 lint
        run: flake8

      - name: Build and test
        run: |
          ./gen.sh
          pytest tests

  automerge:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: fastify/github-action-merge-dependabot@v3.3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
